### ISSUE TITLE
Doc Length remains the compressed value

### ISSUE THREAD

**Issue by felipemoraes** [searchivarius/YahooAnswersLuceneBaseline#1]
Hi Leonid,

I have read your blog and I was wondering if document norm that you used in score(int doc, float freq) should be the "real" document length. I got a value that I assume is the compressed value.
What exactly did you fix on BM25SimilarityFix? I thought that you have found a way to use the real document length. What I am missing?

Thanks much.

**Comment by searchivarius** [comment]
Hi,

The compressed value in the old Lucene implementation doesn't come from Lucene API. It is in some sense "compressed" by BM25Similarity itself. Old code (check encodeNormValue):

```
  @Override
  public final long computeNorm(FieldInvertState state) {
    final int numTerms = discountOverlaps ? state.getLength() - state.getNumOverlap() : state.getLength();
    return encodeNormValue(state.getBoost(), numTerms);
  }
```

I simply don't use encodeNormValue:

```
  @Override
  public final long computeNorm(FieldInvertState state) {
    final float numTerms = discountOverlaps ? state.getLength() - state.getNumOverlap() : state.getLength();
    // Dividing by the square of the boost is to mimic behavior of the old BM25 formula
    final float boost = state.getBoost();
    return (long) ( numTerms / (boost*boost) );
  }
```

Note that this value is still going to be **compressed** but it would be a lossless compression. For example, if the length requires 2 bytes to be stored, Lucene will use 2 bytes, not 4.

So, in the old Lucene implementation there were two levels of compression:
1. The lossless compression of the value returned from computeNorm
2. The lossy compression that is done by BM25Similarity itself.

Is this clear?

BTW, I was going to submit a pull request, but Lucene 6.3 broke internal API :-( It's 6.0 incompatible. :-(((

**Comment by felipemoraes** [comment]
It's clear now!

I am trying to find a way to not have a different index for each Lucene similarity that I want to use. In particular, I use a similarity as a baseline and rerank using a different similarity. So I Google it and found your post. 

Have you experienced with indexing with BM25 and using LM after by setting setSimilarity?

Lucene doesn't look research friendly :-(

**Comment by searchivarius** [comment]
Lucene certainly isn't research friendly. But neither are other open-source engines.

Basically, if you want to apply different similarities **without reindexing** you shouldn't do similarity-specific precomputations. In particular, you should store document length "as is".

I didn't try to use LM after things are indexed using a standard BM25. However, pretty much every similarity computation is screwed, because Lucene BM25 mutilates document lengths. 

Another thing to do if you want to avoid re-indexing is to use your own in-memory forward file. Here's an example of doing this https://github.com/oaqa/knn4qa/tree/cikm2016

This is, in fact, how I found Lucene BM25 is not quite good. I compared outcome against my own re-implementation.
